apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-depl
  name: jenkins-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-depl
  template:
    metadata:
      labels:
        app: jenkins-depl
    spec:
      containers:
        - image: jenkins/jenkins:latest
          name: jenkins-container
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: ClusterIP
  selector:
    app: jenkins-svc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /jenkins
            pathType: Prefix
            backend:
              service:
                name: jenkins-svc
                port:
                  number: 8080