#!/usr/bin/env groovy

def gv

pipeline {
  agent any
  tools{
    maven 'Maven'
  }

  stages {
    stage("init") {
      steps {
        script {
          gv = load "./nana-devops-bootcamp/script.groovy"
        }
      }
    }
    stage("prepare") {
      steps {
        script {
          sh "cp -a ./nana-devops-bootcamp/java-maven-app/. ."
        }
      }
    }
    stage("build jar") {
      steps {
        script {
          gv.buildJar()
        }
      }
    }
    stage("build image") {
      steps {
        script {
          gv.buildImage()
        }
      }
    }
    stage("deploy") {
      steps {
        script {
          gv.deployApp()
        }
      }
    }
  }

}